// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameDocQuestion = "doc_question"

// DocQuestion mapped from table <doc_question>
type DocQuestion struct {
	ID         string `gorm:"column:id;type:varchar(255);primaryKey" json:"id"`                 // 文章问题id
	DocID      string `gorm:"column:doc_id;type:varchar(255);not null" json:"doc_id"`           // 文章id
	QuestionID string `gorm:"column:question_id;type:varchar(255);not null" json:"question_id"` // 问题id
}

// TableName DocQuestion's table name
func (*DocQuestion) TableName() string {
	return TableNameDocQuestion
}
