// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameExchangeGift = "exchange_gift"

// ExchangeGift mapped from table <exchange_gift>
type ExchangeGift struct {
	ID     string `gorm:"column:id;type:varchar(255);primaryKey" json:"id"` // 礼物兑换id
	UserID string `gorm:"column:user_id;type:varchar(255)" json:"user_id"`  // 用户id
	GiftID string `gorm:"column:gift_id;type:varchar(255)" json:"gift_id"`  // 物品id
	Count  int64  `gorm:"column:count;type:int" json:"count"`               // 兑换数量
	Time   int64  `gorm:"column:time;type:bigint" json:"time"`              // 兑换时间
}

// TableName ExchangeGift's table name
func (*ExchangeGift) TableName() string {
	return TableNameExchangeGift
}
