// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameForm = "form"

// Form mapped from table <form>
type Form struct {
	ID      string `gorm:"column:id;type:varchar(255);primaryKey" json:"id"`
	Type    int64  `gorm:"column:type;type:tinyint" json:"type"`             // 通知类型
	UserID  string `gorm:"column:user_id;type:varchar(255)" json:"user_id"`  // 用户id
	MapID   string `gorm:"column:map_id;type:varchar(255)" json:"map_id"`    // 地图id
	Content string `gorm:"column:content;type:varchar(1000)" json:"content"` // 通知内容
	Source  int64  `gorm:"column:source;type:tinyint" json:"source"`         // 来源
}

// TableName Form's table name
func (*Form) TableName() string {
	return TableNameForm
}
