// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameMap = "map"

// Map mapped from table <map>
type Map struct {
	ID     string `gorm:"column:id;type:varchar(255);primaryKey" json:"id"`
	Name   string `gorm:"column:name;type:varchar(255)" json:"name"`   // 名称
	Image  string `gorm:"column:image;type:varchar(255)" json:"image"` // 图片
	Width  int64  `gorm:"column:width;type:int" json:"width"`          // 宽
	Height int64  `gorm:"column:height;type:int" json:"height"`        // 高
}

// TableName Map's table name
func (*Map) TableName() string {
	return TableNameMap
}
