// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameMonsterQuestion = "monster_question"

// MonsterQuestion mapped from table <monster_question>
type MonsterQuestion struct {
	ID         string `gorm:"column:id;type:varchar(255);primaryKey" json:"id"`        // 怪物问题Id
	MonsterID  string `gorm:"column:monster_id;type:varchar(255)" json:"monster_id"`   // 怪物id
	QuestionID string `gorm:"column:question_id;type:varchar(255)" json:"question_id"` // 问题id
}

// TableName MonsterQuestion's table name
func (*MonsterQuestion) TableName() string {
	return TableNameMonsterQuestion
}
