// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameNpcTask = "npc_task"

// NpcTask mapped from table <npc_task>
type NpcTask struct {
	ID     string `gorm:"column:id;type:varchar(255);primaryKey" json:"id"` // npc持有任务id
	NpcID  string `gorm:"column:npc_id;type:varchar(255)" json:"npc_id"`    // npc id
	TaskID string `gorm:"column:task_id;type:varchar(255)" json:"task_id"`  // 任务id
}

// TableName NpcTask's table name
func (*NpcTask) TableName() string {
	return TableNameNpcTask
}
