// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameQuestionAnswer = "question_answer"

// QuestionAnswer mapped from table <question_answer>
type QuestionAnswer struct {
	ID         string `gorm:"column:id;type:varchar(255);primaryKey" json:"id"`        // id
	QuestionID string `gorm:"column:question_id;type:varchar(255)" json:"question_id"` // 问题id
	Answer     string `gorm:"column:answer;type:varchar(255)" json:"answer"`           // 答案-选择项的id
}

// TableName QuestionAnswer's table name
func (*QuestionAnswer) TableName() string {
	return TableNameQuestionAnswer
}
