// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameQuestionSelect = "question_select"

// QuestionSelect mapped from table <question_select>
type QuestionSelect struct {
	ID         string `gorm:"column:id;type:varchar(255);primaryKey" json:"id"`        // id
	QuestionID string `gorm:"column:question_id;type:varchar(255)" json:"question_id"` // 问题id
	Content    string `gorm:"column:content;type:varchar(255)" json:"content"`         // 选项内容
}

// TableName QuestionSelect's table name
func (*QuestionSelect) TableName() string {
	return TableNameQuestionSelect
}
