// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameQuestion = "question"

// Question mapped from table <question>
type Question struct {
	ID        string `gorm:"column:id;type:varchar(255);primaryKey" json:"id"`      // 问答题id
	Level     int64  `gorm:"column:level;type:int" json:"level"`                    // 题目等级
	Type      int64  `gorm:"column:type;type:int" json:"type"`                      // 题目分类
	QuestionA string `gorm:"column:question_a;type:varchar(255)" json:"question_a"` // A选项
	QuestionB string `gorm:"column:question_b;type:varchar(255)" json:"question_b"` // B选项
	QuestionC string `gorm:"column:question_c;type:varchar(255)" json:"question_c"` // C选项
	QuestionD string `gorm:"column:question_d;type:varchar(255)" json:"question_d"` // D选项
	Answer    string `gorm:"column:answer;type:varchar(255)" json:"answer"`         // 答案
	Damage    int64  `gorm:"column:damage;type:int" json:"damage"`                  // 题目伤害
}

// TableName Question's table name
func (*Question) TableName() string {
	return TableNameQuestion
}
