// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameTask = "task"

// Task mapped from table <task>
type Task struct {
	ID           string `gorm:"column:id;type:varchar(255);primaryKey" json:"id"`          // 任务id
	Type         int64  `gorm:"column:type;type:int" json:"type"`                          // 任务类型 1-打怪类 2-阅读任务 3-附件任务
	Level        int64  `gorm:"column:level;type:int" json:"level"`                        // 任务等级
	Introduction string `gorm:"column:introduction;type:varchar(255)" json:"introduction"` // 任务描述
	Image        string `gorm:"column:image;type:varchar(255)" json:"image"`               // 图片链接
	Experience   int64  `gorm:"column:experience;type:int" json:"experience"`              // 经验奖励
	Coin         int64  `gorm:"column:coin;type:int" json:"coin"`                          // 金币奖励
}

// TableName Task's table name
func (*Task) TableName() string {
	return TableNameTask
}
