// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"education/model"
)

func newForm(db *gorm.DB, opts ...gen.DOOption) form {
	_form := form{}

	_form.formDo.UseDB(db, opts...)
	_form.formDo.UseModel(&model.Form{})

	tableName := _form.formDo.TableName()
	_form.ALL = field.NewAsterisk(tableName)
	_form.ID = field.NewString(tableName, "id")
	_form.Type = field.NewInt64(tableName, "type")
	_form.UserID = field.NewString(tableName, "user_id")
	_form.MapID = field.NewString(tableName, "map_id")
	_form.Content = field.NewString(tableName, "content")
	_form.Source = field.NewInt64(tableName, "source")

	_form.fillFieldMap()

	return _form
}

type form struct {
	formDo formDo

	ALL     field.Asterisk
	ID      field.String
	Type    field.Int64  // 通知类型
	UserID  field.String // 用户id
	MapID   field.String // 地图id
	Content field.String // 通知内容
	Source  field.Int64  // 来源

	fieldMap map[string]field.Expr
}

func (f form) Table(newTableName string) *form {
	f.formDo.UseTable(newTableName)
	return f.updateTableName(newTableName)
}

func (f form) As(alias string) *form {
	f.formDo.DO = *(f.formDo.As(alias).(*gen.DO))
	return f.updateTableName(alias)
}

func (f *form) updateTableName(table string) *form {
	f.ALL = field.NewAsterisk(table)
	f.ID = field.NewString(table, "id")
	f.Type = field.NewInt64(table, "type")
	f.UserID = field.NewString(table, "user_id")
	f.MapID = field.NewString(table, "map_id")
	f.Content = field.NewString(table, "content")
	f.Source = field.NewInt64(table, "source")

	f.fillFieldMap()

	return f
}

func (f *form) WithContext(ctx context.Context) IFormDo { return f.formDo.WithContext(ctx) }

func (f form) TableName() string { return f.formDo.TableName() }

func (f form) Alias() string { return f.formDo.Alias() }

func (f *form) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := f.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (f *form) fillFieldMap() {
	f.fieldMap = make(map[string]field.Expr, 6)
	f.fieldMap["id"] = f.ID
	f.fieldMap["type"] = f.Type
	f.fieldMap["user_id"] = f.UserID
	f.fieldMap["map_id"] = f.MapID
	f.fieldMap["content"] = f.Content
	f.fieldMap["source"] = f.Source
}

func (f form) clone(db *gorm.DB) form {
	f.formDo.ReplaceConnPool(db.Statement.ConnPool)
	return f
}

func (f form) replaceDB(db *gorm.DB) form {
	f.formDo.ReplaceDB(db)
	return f
}

type formDo struct{ gen.DO }

type IFormDo interface {
	gen.SubQuery
	Debug() IFormDo
	WithContext(ctx context.Context) IFormDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IFormDo
	WriteDB() IFormDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IFormDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IFormDo
	Not(conds ...gen.Condition) IFormDo
	Or(conds ...gen.Condition) IFormDo
	Select(conds ...field.Expr) IFormDo
	Where(conds ...gen.Condition) IFormDo
	Order(conds ...field.Expr) IFormDo
	Distinct(cols ...field.Expr) IFormDo
	Omit(cols ...field.Expr) IFormDo
	Join(table schema.Tabler, on ...field.Expr) IFormDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IFormDo
	RightJoin(table schema.Tabler, on ...field.Expr) IFormDo
	Group(cols ...field.Expr) IFormDo
	Having(conds ...gen.Condition) IFormDo
	Limit(limit int) IFormDo
	Offset(offset int) IFormDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IFormDo
	Unscoped() IFormDo
	Create(values ...*model.Form) error
	CreateInBatches(values []*model.Form, batchSize int) error
	Save(values ...*model.Form) error
	First() (*model.Form, error)
	Take() (*model.Form, error)
	Last() (*model.Form, error)
	Find() ([]*model.Form, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Form, err error)
	FindInBatches(result *[]*model.Form, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.Form) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IFormDo
	Assign(attrs ...field.AssignExpr) IFormDo
	Joins(fields ...field.RelationField) IFormDo
	Preload(fields ...field.RelationField) IFormDo
	FirstOrInit() (*model.Form, error)
	FirstOrCreate() (*model.Form, error)
	FindByPage(offset int, limit int) (result []*model.Form, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IFormDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (f formDo) Debug() IFormDo {
	return f.withDO(f.DO.Debug())
}

func (f formDo) WithContext(ctx context.Context) IFormDo {
	return f.withDO(f.DO.WithContext(ctx))
}

func (f formDo) ReadDB() IFormDo {
	return f.Clauses(dbresolver.Read)
}

func (f formDo) WriteDB() IFormDo {
	return f.Clauses(dbresolver.Write)
}

func (f formDo) Session(config *gorm.Session) IFormDo {
	return f.withDO(f.DO.Session(config))
}

func (f formDo) Clauses(conds ...clause.Expression) IFormDo {
	return f.withDO(f.DO.Clauses(conds...))
}

func (f formDo) Returning(value interface{}, columns ...string) IFormDo {
	return f.withDO(f.DO.Returning(value, columns...))
}

func (f formDo) Not(conds ...gen.Condition) IFormDo {
	return f.withDO(f.DO.Not(conds...))
}

func (f formDo) Or(conds ...gen.Condition) IFormDo {
	return f.withDO(f.DO.Or(conds...))
}

func (f formDo) Select(conds ...field.Expr) IFormDo {
	return f.withDO(f.DO.Select(conds...))
}

func (f formDo) Where(conds ...gen.Condition) IFormDo {
	return f.withDO(f.DO.Where(conds...))
}

func (f formDo) Exists(subquery interface{ UnderlyingDB() *gorm.DB }) IFormDo {
	return f.Where(field.CompareSubQuery(field.ExistsOp, nil, subquery.UnderlyingDB()))
}

func (f formDo) Order(conds ...field.Expr) IFormDo {
	return f.withDO(f.DO.Order(conds...))
}

func (f formDo) Distinct(cols ...field.Expr) IFormDo {
	return f.withDO(f.DO.Distinct(cols...))
}

func (f formDo) Omit(cols ...field.Expr) IFormDo {
	return f.withDO(f.DO.Omit(cols...))
}

func (f formDo) Join(table schema.Tabler, on ...field.Expr) IFormDo {
	return f.withDO(f.DO.Join(table, on...))
}

func (f formDo) LeftJoin(table schema.Tabler, on ...field.Expr) IFormDo {
	return f.withDO(f.DO.LeftJoin(table, on...))
}

func (f formDo) RightJoin(table schema.Tabler, on ...field.Expr) IFormDo {
	return f.withDO(f.DO.RightJoin(table, on...))
}

func (f formDo) Group(cols ...field.Expr) IFormDo {
	return f.withDO(f.DO.Group(cols...))
}

func (f formDo) Having(conds ...gen.Condition) IFormDo {
	return f.withDO(f.DO.Having(conds...))
}

func (f formDo) Limit(limit int) IFormDo {
	return f.withDO(f.DO.Limit(limit))
}

func (f formDo) Offset(offset int) IFormDo {
	return f.withDO(f.DO.Offset(offset))
}

func (f formDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IFormDo {
	return f.withDO(f.DO.Scopes(funcs...))
}

func (f formDo) Unscoped() IFormDo {
	return f.withDO(f.DO.Unscoped())
}

func (f formDo) Create(values ...*model.Form) error {
	if len(values) == 0 {
		return nil
	}
	return f.DO.Create(values)
}

func (f formDo) CreateInBatches(values []*model.Form, batchSize int) error {
	return f.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (f formDo) Save(values ...*model.Form) error {
	if len(values) == 0 {
		return nil
	}
	return f.DO.Save(values)
}

func (f formDo) First() (*model.Form, error) {
	if result, err := f.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Form), nil
	}
}

func (f formDo) Take() (*model.Form, error) {
	if result, err := f.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Form), nil
	}
}

func (f formDo) Last() (*model.Form, error) {
	if result, err := f.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Form), nil
	}
}

func (f formDo) Find() ([]*model.Form, error) {
	result, err := f.DO.Find()
	return result.([]*model.Form), err
}

func (f formDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Form, err error) {
	buf := make([]*model.Form, 0, batchSize)
	err = f.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (f formDo) FindInBatches(result *[]*model.Form, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return f.DO.FindInBatches(result, batchSize, fc)
}

func (f formDo) Attrs(attrs ...field.AssignExpr) IFormDo {
	return f.withDO(f.DO.Attrs(attrs...))
}

func (f formDo) Assign(attrs ...field.AssignExpr) IFormDo {
	return f.withDO(f.DO.Assign(attrs...))
}

func (f formDo) Joins(fields ...field.RelationField) IFormDo {
	for _, _f := range fields {
		f = *f.withDO(f.DO.Joins(_f))
	}
	return &f
}

func (f formDo) Preload(fields ...field.RelationField) IFormDo {
	for _, _f := range fields {
		f = *f.withDO(f.DO.Preload(_f))
	}
	return &f
}

func (f formDo) FirstOrInit() (*model.Form, error) {
	if result, err := f.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Form), nil
	}
}

func (f formDo) FirstOrCreate() (*model.Form, error) {
	if result, err := f.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Form), nil
	}
}

func (f formDo) FindByPage(offset int, limit int) (result []*model.Form, count int64, err error) {
	result, err = f.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = f.Offset(-1).Limit(-1).Count()
	return
}

func (f formDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = f.Count()
	if err != nil {
		return
	}

	err = f.Offset(offset).Limit(limit).Scan(result)
	return
}

func (f formDo) Scan(result interface{}) (err error) {
	return f.DO.Scan(result)
}

func (f formDo) Delete(models ...*model.Form) (result gen.ResultInfo, err error) {
	return f.DO.Delete(models)
}

func (f *formDo) withDO(do gen.Dao) *formDo {
	f.DO = *do.(*gen.DO)
	return f
}
